"""initial schema

Revision ID: dc37d339453f
Revises: 
Create Date: 2026-06-21 16:22:22.986899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc37d339453f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_note_tags_note_id'), table_name='note_tags')
    op.drop_index(op.f('idx_note_tags_tag'), table_name='note_tags')
    op.drop_table('note_tags')
    op.drop_index(op.f('idx_habit_logs_habit_id_date'), table_name='habit_logs')
    op.drop_index(op.f('idx_habit_logs_unique_day'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.add_column('habits', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('habits', 'frequency',
               existing_type=postgresql.ARRAY(sa.SMALLINT()),
               type_=postgresql.ARRAY(sa.Integer()),
               existing_nullable=False)
    op.drop_index(op.f('idx_habits_user_id'), table_name='habits')
    op.drop_constraint(op.f('habits_user_id_fkey'), 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'users', ['user_id'], ['id'])
    op.drop_column('habits', 'createdat')
    op.drop_index(op.f('idx_notes_user_id'), table_name='notes')
    op.drop_constraint(op.f('notes_user_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'No description'::text"))
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('frequency', postgresql.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frequency')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'No description'::text"))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_user_id_fkey'), 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.add_column('habits', sa.Column('createdat', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key(op.f('habits_user_id_fkey'), 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.alter_column('habits', 'frequency',
               existing_type=postgresql.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.SMALLINT()),
               existing_nullable=False)
    op.drop_column('habits', 'completed_at')
    op.create_table('habit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('habit_logs_habit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('habit_logs_pkey'))
    )
    op.create_index(op.f('idx_habit_logs_unique_day'), 'habit_logs', ['habit_id', sa.literal_column('(logged_at::date)')], unique=True)
    op.create_index(op.f('idx_habit_logs_habit_id_date'), 'habit_logs', ['habit_id', sa.literal_column('logged_at DESC')], unique=False)
    op.create_table('note_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('note_tags_note_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('note_tags_pkey'))
    )
    op.create_index(op.f('idx_note_tags_tag'), 'note_tags', ['tag'], unique=False)
    op.create_index(op.f('idx_note_tags_note_id'), 'note_tags', ['note_id'], unique=False)
    # ### end Alembic commands ###
